parameters:
    canabelle_cms_translation.default.service.translation.class: Canabelle\CMSTranslationBundle\TranslationForm\TranslationForm
    canabelle_cms_translation.default.listener.translations.class: Canabelle\CMSTranslationBundle\Form\EventListener\TranslationsListener
    canabelle_cms_translation.default.listener.translationsForms.class: Canabelle\CMSTranslationBundle\Form\EventListener\TranslationsFormsListener
    canabelle_cms_translation.default.type.translations.class: Canabelle\CMSTranslationBundle\Form\Type\TranslationsType
    canabelle_cms_translation.default.type.translationsFields.class: Canabelle\CMSTranslationBundle\Form\Type\TranslationsFieldsType
    canabelle_cms_translation.default.type.translationsForms.class: Canabelle\CMSTranslationBundle\Form\Type\TranslationsFormsType
    canabelle_cms_translation.default.type.translationsLocalesSelector.class: Canabelle\CMSTranslationBundle\Form\Type\TranslationsLocalesSelectorType
    canabelle_cms_translation.default.type.translatedEntity.class: Canabelle\CMSTranslationBundle\Form\Type\TranslatedEntityType
    canabelle_cms_translation.translationsDataCollector.class: Canabelle\CMSTranslationBundle\DataCollector\TranslationsDataCollector

services:
    translation.loader.db:
        class: Canabelle\CMSTranslationBundle\Services\DBLoader
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: translation.loader, alias: db }

    kernel.listener.resource_listener:
        class: Canabelle\CMSTranslationBundle\EventListener\ResourceListener
        arguments: [@translator, @sonata.page.site.selector]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 39 }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -120 }

    canabelle_cms_translation.resource:
        class: Canabelle\CMSTranslationBundle\Config\Resource\TranslationDBResource
        arguments: ['@translation.loader.db']

    canabelle_cms_translation.default.service.translation:
        class: %canabelle_cms_translation.default.service.translation.class%
        arguments: [@form.registry, @canabelle_cms_translation.manager_registry]

    canabelle_cms_translation.default.listener.translations:
        class: %canabelle_cms_translation.default.listener.translations.class%
        arguments: [@canabelle_cms_translation.default.service.translation]

    canabelle_cms_translation.default.listener.translationsForms:
        class: %canabelle_cms_translation.default.listener.translationsForms.class%

    canabelle_cms_translation.default.type.translations:
        class: %canabelle_cms_translation.default.type.translations.class%
        arguments: [@canabelle_cms_translation.default.listener.translations, %canabelle_cms_translation.locales%, %canabelle_cms_translation.default_locale%, %canabelle_cms_translation.required_locales%]
        tags:
            - { name: form.type, alias: canabelle_cms_translations }

    canabelle_cms_translation.default.type.translationsFields:
        class: %canabelle_cms_translation.default.type.translationsFields.class%
        tags:
            - { name: form.type, alias: canabelle_cms_translationsFields }

    canabelle_cms_translation.default.type.translationsForms:
        class: %canabelle_cms_translation.default.type.translationsForms.class%
        arguments: [@canabelle_cms_translation.default.service.translation, @canabelle_cms_translation.default.listener.translationsForms, %canabelle_cms_translation.locales%, %canabelle_cms_translation.default_locale%, %canabelle_cms_translation.required_locales%]
        tags:
            - { name: form.type, alias: canabelle_cms_translationsForms }

    canabelle_cms_translation.default.type.translationsLocalesSelector:
        class: %canabelle_cms_translation.default.type.translationsLocalesSelector.class%
        arguments: [%canabelle_cms_translation.locales%, %canabelle_cms_translation.default_locale%]
        tags:
            - { name: form.type, alias: canabelle_cms_translationsLocalesSelector }

    canabelle_cms_translation.default.type.translatedEntity:
        class: %canabelle_cms_translation.default.type.translatedEntity.class%
        calls:
            - [ setRequest, [@request_stack] ]
        tags:
            - { name: form.type, alias: canabelle_cms_translatedEntity }

    canabelle_cms_translation.language_token.repository:
        class:           Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [Canabelle\CMSTranslationBundle\Entity\LanguageToken]

    canabelle_cms_translation.language_catalogue.repository:
        class:           Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [Canabelle\CMSTranslationBundle\Entity\LanguageCatalogue]

    canabelle_cms_translation.data_collector.translations:
        class: %canabelle_cms_translation.translationsDataCollector.class%
        arguments: [@translator.default, @canabelle_cms_translation.language_catalogue.repository]
        tags:
            - { name: data_collector, template: 'CanabelleCMSTranslationBundle:DataCollector:translations.html.twig', id: 'canabelle_cms_translation.data_collector.translations', priority: 1 }

